name: 'docs'

on:
  registry_package:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run build:docs

      - name: Identity
        run: |
          git config --global user.email "netanel7799@gmail.com"
          git config --global user.name "NetanelBasal"

      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: NetanelBasal
        run: npm run deploy --prefix docs
